[package]
name = "dcs-dach-bot"
version = "0.1.0"
edition = "2021"

# https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
serenity = { version = "0.11", default-features = false, features = ["builder", "client", "cache", "gateway", "rustls_backend", "model", "utils"] }
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
