# fly.toml file generated for dcs-dach-bot on 2023-01-21T14:57:00+01:00

app = "dcs-dach-bot-live"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  CHANNELID_ALL = "951858030243373117"
  CHANNELID_ONLINE = "846769112684036106"
  CHANNELID_MOD = "1076595614353215499"
  GUILD_ID = "691838795049599027"


[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]