# fly.toml file generated for dcs-dach-bot on 2023-01-21T14:57:00+01:00

app = "dcs-dach-bot-test"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  CHANNELID_ALL = "1028632535418290257"
  CHANNELID_ONLINE = "1029107882978975795"
  CHANNELID_MOD = "1040597438597173279"
  GUILD_ID = "1028451968588451920"


[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]