on:
  push:
    branches:
      - main
  pull_request:

name: CI

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
          - "ubuntu-24.04-arm"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Inatsll nix
        uses: DeterminateSystems/nix-installer-action@v20
      - name: Run checks via nix
        run: nix flake check -L
      - name: Get codecov
        run: nix build .#tarpaulin
      - name: Upload Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./result/cobertura.xml
